name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_svg: ^2.0.5
  http: ^0.13.6
  intl: ^0.17.0
  search: ^0.3.0
  shared_preferences: ^2.2.2
  simple_animations: ^5.0.2
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/medicine1.jpeg
    - assets/medicine2.jpeg
    - assets/medicine3.jpeg
    - assets/medicine4.jpeg
    - assets/medicine5.jpeg
    - assets/medicine6.jpeg
    - assets/medicine7.jpeg
    - assets/medicine8.jpeg

